language: go
dist: xenial
go:
  - 1.13.x

services:
  - docker

addons:
  apt:
    packages: [liblzo2-dev]

env:
  global:
    - TEST_MODIFIER=-race
    - CACHE_FOLDER=$HOME/docker-images
    - IMAGE=wal-g/docker_prefix
    - IMAGE_UBUNTU=wal-g/ubuntu
    - IMAGE_GOLANG=wal-g/golang
    - CACHE_FILE_UBUNTU=${CACHE_FOLDER}/wal-g_ubuntu-${TRAVIS_COMMIT}.tgz
    - CACHE_FILE_GOLANG=${CACHE_FOLDER}/wal-g_golang-${TRAVIS_COMMIT}.tgz
    - CACHE_FILE_DOCKER_PREFIX=${CACHE_FOLDER}/docker_prefix-${TRAVIS_COMMIT}.tgz

jobs:
  include:
    - stage: build image
      env:
        - USE_LZO=1
      script: make pg_save_image
      workspaces:
        create:
          name: image_cache
          paths:
            - ${CACHE_FILE_DOCKER_PREFIX}
            - ${CACHE_FILE_UBUNTU}
            - ${CACHE_FILE_GOLANG}
    - stage: test
      env:
      - USE_LIBSODIUM=1
      - USE_LZO=1
      script: make all_unittests
    - script: make TEST="pg_backup_mark_impermanent_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_backup_mark_permanent_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_config_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_crypto_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_delta_backup_wal_delta_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_full_backup_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_ssh_backup_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_receive_wal_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_full_backup_rating_composer_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_delete_before_name_find_full_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_delete_retain_full_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_delete_before_time_find_full_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_delete_without_confirm_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_ghost_table_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_delete_end_to_end_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_delta_backup_fullscan_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_several_delta_backups_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_several_delta_backups_reverse_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_delete_retain_find_full_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_wale_compatibility_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_delete_before_permanent_full_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_delete_before_permanent_delta_test" pg_integration_test
      workspaces:
        use: image_cache
      workspaces:
        use: image_cache
    - script: make mongo_test
      workspaces:
        use: image_cache
    - script: make MONGO_VERSION="4.4.0" MONGO_MAJOR="4.4" mongo_features
      workspaces:
        use: image_cache
    - script: make MONGO_VERSION="4.2.8" MONGO_MAJOR="4.2" mongo_features
      workspaces:
        use: image_cache
    - script: make MONGO_FEATURE="backup" MONGO_VERSION="4.0.19" MONGO_MAJOR="4.0" mongo_features
      workspaces:
        use: image_cache
    - script: make MONGO_FEATURE="backup" MONGO_VERSION="3.6.19" MONGO_MAJOR="3.6" mongo_features
      workspaces:
        use: image_cache
    - script: make redis_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_wale_tablespace_compatibility_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_tablespace_support_test" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_wal_perftest" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_backup_perftest" pg_integration_test
      workspaces:
        use: image_cache
    - script: make TEST="pg_catchup_test" pg_integration_test
      workspaces:
        use: image_cache


notifications:
  email: false

before_deploy:
  - tar -zcf wal-g.linux-amd64.tar.gz -C main/pg wal-g
  - sha256sum wal-g.linux-amd64.tar.gz > wal-g.linux-amd64.tar.gz.sha256

deploy:
  provider: releases
  api_key:
    secure: nRVV5uKaBdCi/J/sLP7+c/shuDEaSeMiapEsro5gp4gr8n/QMgGm5AHNZhkfQVBmhmaKNB7dDzg34RVD2qacVpeZQTTUWetorBiwWvSjf+mlVcmBPKOIivamqetIdMEPgGQ0vudDADMpYiiqWBV893vAg1w0x02Cz7yvduzKEDyVttH+P4A7MPZ9tPtwLyMoOKjxe7Z0IOp82DK0rj+2KXQYe+El9Ipya+2WB88NBuRn2dJSfsAx9VI+5VmUz0waB1lP3ityjgQpaL13QEV6qsCXl+ntb4vGACbPYoPt0pgesq/zkL2ScFKTbzSSo6yByf3zHhV+elZ2sXnK/UYrqe4erC3qkG5qiTuy+uzPKg0pOVdqI1kDtMNoIanCjSVblXXsR+vz0UVHbzOmTMm7ckpnMB1nxsSyaQfs1C2e42SCgIB57RJsWUSsRx/Uq9iJS32ab/8pSnzJ2dZLNo4BxNHJDgKpmfj6ZKhBne+JUcfBsx2DOXs1ad9s0+ahpnlLiijhQQ5ZxGTfzYcXjijtAOyN2Y42wU6YI3L7ezsZTw+AoJeBMdc2MM8yy1CI/PM0x5IL+e9cZ+LoL87f0WZFxMd0KYblEeQzL+yRv0M5cRf4GPgqgEFsYUU4WXAH6Fnah2dailOvkfV1ygbaTxjvrSiIDnk0DKls3y8QLwSJPLw=
  skip_cleanup: true
  file:
    - wal-g.linux-amd64.tar.gz
    - wal-g.linux-amd64.tar.gz.sha256
  on:
    repo: wal-g/wal-g
    tags: true
