version: '3'

services:
  golang:
    build:
      dockerfile: ./docker/golang/Dockerfile
      context: .
    image: wal-g/golang
    container_name: wal-g_golang

  ubuntu:
    build:
      dockerfile: ./docker/ubuntu/Dockerfile
      context: .
    image: wal-g/ubuntu
    container_name: wal-g_ubuntu

  s3:
    image: minio/minio
    container_name: wal-g_s3
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    entrypoint: sh
    command: >
      -c 'mkdir -p /export/fullbucket
      &&  mkdir -p /export/fullscandeltabucket
      &&  mkdir -p /export/cryptobucket
      &&  mkdir -p /export/waldeltabucket
      &&  mkdir -p /export/ghostbucket
      &&  mkdir -p /export/compressionbucket
      &&  mkdir -p /export/deleteretainfullbucket
      &&  mkdir -p /export/deleteretainfindfullbucket
      &&  mkdir -p /export/deletebeforenamefindfullbucket
      &&  mkdir -p /export/deletebeforetimefindfullbucket
      &&  mkdir -p /export/deletewithoutconfirm
      &&  mkdir -p /export/deleteendtoendbucket
      &&  mkdir -p /export/mysqlfullbucket
      &&  mkdir -p /export/mysqlbinlogpushbucket
      &&  mkdir -p /export/mysqldeleteendtoendbucket
      &&  mkdir -p /export/mongostreampushbucket
      &&  mkdir -p /export/mongooplogpushbucket
      &&  mkdir -p /export/mongodeletebeforebucket
      &&  mkdir -p /export/mongodeleteretainbucket
      &&  mkdir -p /export/redisbucket
      &&  /usr/bin/minio server /export'

  pg:
    build:
      dockerfile: docker/pg/Dockerfile
      context: .
    image: wal-g/pg
    container_name: wal-g_pg

  pg_tests:
    build:
      dockerfile: docker/pg_tests/Dockerfile
      context: .
    image: wal-g/pg_tests
    container_name: wal-g_pg_tests
    env_file:
      - docker/common/common_walg.env
      - docker/pg_tests/walg.env
    depends_on:
      - s3
    links:
      - s3

  pg_crypto_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_crypto_test
      context: .
    image: wal-g/pg_crypto_test
    container_name: wal-g_pg_crypto_test
    env_file:
      - docker/common/common_walg.env
      - docker/pg_tests/walg.env
    depends_on:
      - s3
    links:
      - s3

  pg_config_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_config_test
      context: .
    image: wal-g/pg_config_test
    container_name: wal-g_pg_config_test
    env_file:
      - docker/common/common_walg.env
      - docker/pg_tests/walg.env
    depends_on:
      - s3
    links:
      - s3

  mysql:
    build:
      dockerfile: docker/mysql/Dockerfile
      context: .
    image: wal-g/mysql
    container_name: wal-g_mysql

  mysql_tests:
    build:
      dockerfile: docker/mysql_tests/Dockerfile
      context: .
    image: wal-g/mysql_tests
    container_name: wal-g_mysql_tests
    env_file:
      - docker/common/common_walg.env
      - docker/mysql_tests/walg.env
    depends_on:
      - s3
    links:
      - s3

  redis:
    build:
      dockerfile: docker/redis/Dockerfile
      context: .
    image: wal-g/redis
    container_name: wal-g_redis

  redis_tests:
    build:
      dockerfile: docker/redis_tests/Dockerfile
      context: .
    image: wal-g/redis_tests
    container_name: wal-g_redis_tests
    env_file:
      - docker/common/common_walg.env
    depends_on:
      - s3
    links:
      - s3

  mongo:
    build:
      dockerfile: docker/mongo/Dockerfile
      context: .
    image: wal-g/mongo
    container_name: wal-g_mongo

  mongo_tests:
    build:
      dockerfile: docker/mongo_tests/Dockerfile
      context: .
    image: wal-g/mongo_tests
    container_name: wal-g_mongo_tests
    env_file:
      - docker/common/common_walg.env
    depends_on:
      - s3
    links:
      - s3
