version: '3'

volumes:
  fdb_volume:

services:
  golang:
    build:
      dockerfile: ./docker/golang/Dockerfile
      context: .
    image: wal-g/golang
    container_name: wal-g_golang

  ubuntu:
    build:
      dockerfile: ./docker/ubuntu/Dockerfile
      context: .
    image: wal-g/ubuntu
    container_name: wal-g_ubuntu

  s3:
    image: minio/minio
    container_name: wal-g_s3
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    entrypoint: sh
    command: >
      -c 'mkdir -p /export/fullbucket
      &&  mkdir -p /export/fullratingcomposerbucket
      &&  mkdir -p /export/fullscandeltabucket
      &&  mkdir -p /export/cryptobucket
      &&  mkdir -p /export/waldeltabucket
      &&  mkdir -p /export/ghostbucket
      &&  mkdir -p /export/compressionbucket
      &&  mkdir -p /export/copyallbucket
      &&  mkdir -p /export/copybackupbucket
      &&  mkdir -p /export/compressionreversebucket
      &&  mkdir -p /export/deleteretainfullbucket
      &&  mkdir -p /export/deleteretainfindfullbucket
      &&  mkdir -p /export/deletebeforenamefindfullbucket
      &&  mkdir -p /export/deletebeforetimefindfullbucket
      &&  mkdir -p /export/deletebeforepermanentfullbucket
      &&  mkdir -p /export/deletebeforepermanentdeltabucket
      &&  mkdir -p /export/deletewithoutconfirm
      &&  mkdir -p /export/deleteendtoendbucket
      &&  mkdir -p /export/mysqlfullxtrabackupbucket
      &&  mkdir -p /export/mysqlfullmysqldumpbucket
      &&  mkdir -p /export/mysqlbinlogpushfetchbucket
      &&  mkdir -p /export/mysqldeleteendtoendbucket
      &&  mkdir -p /export/mysqlbinlogreplaybucket
      &&  mkdir -p /export/mysqlpitrxtrabackupbucket
      &&  mkdir -p /export/mysqlpitrmysqldumpbucket
      &&  mkdir -p /export/mariadbfullmysqldumpbucket
      &&  mkdir -p /export/mariadbfullmariabackupbucket
      &&  mkdir -p /export/mongostreampushbucket
      &&  mkdir -p /export/mongooplogpushbucket
      &&  mkdir -p /export/mongodeletebeforebucket
      &&  mkdir -p /export/mongodeleteretainbucket
      &&  mkdir -p /export/redisbucket
      &&  mkdir -p /export/mysqlcopybackupfrom
      &&  mkdir -p /export/mysqlcopybackupto
      &&  mkdir -p /export/mysqlconfonly
      &&  /usr/bin/minio server /export'

  s3-another:
    image: minio/minio
    container_name: wal-g_s32
    ports:
      - "9001:9001"
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLEBUTANOHER"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEYBUTANOTHERTOO"
    entrypoint: sh
    command: >
      -c 'mkdir -p /export/mysqlcopybackupto
      &&  /usr/bin/minio server /export'

  ssh:
    build:
      dockerfile: docker/ssh/Dockerfile
      context: .
    container_name: wal-g_ssh
    ports:
      - "6942:6942"

  pg:
    build:
      dockerfile: docker/pg/Dockerfile
      context: .
    image: wal-g/pg
    container_name: wal-g_pg

  pg_tests:
    build:
      dockerfile: docker/pg_tests/Dockerfile
      context: .
    image: wal-g/pg_tests
    container_name: wal-g_pg_tests

  pg_build_docker_prefix:
    build:
      dockerfile: docker/pg_tests/Dockerfile_prefix
      context: .
    image: wal-g/docker_prefix
    container_name: wal-g_pg_docker_prefix
    depends_on:
      - s3
    links:
      - s3

  pg_delete_before_permanent_full_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_delete_before_permanent_full_test
      context: .
    image: wal-g/delete_before_permanent_full_test
    container_name: wal-g_pg_delete_before_permanent_full_test
    depends_on:
      - s3
    links:
      - s3

  pg_backup_mark_permanent_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_backup_mark_permanent_test
      context: .
    image: wal-g/backup_mark_permanent_test
    container_name: wal-g_pg_backup_mark_permanent_test
    depends_on:
      - s3
    links:
      - s3

  pg_backup_mark_impermanent_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_backup_mark_impermanent_test
      context: .
    image: wal-g/backup_mark_impermanent_test
    container_name: wal-g_pg_backup_mark_impermanent_test
    depends_on:
      - s3
    links:
      - s3


  pg_delete_before_permanent_delta_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_delete_before_permanent_delta_test
      context: .
    image: wal-g/delete_before_permanent_delta_test
    container_name: wal-g_pg_delete_before_permanent_delta_test
    depends_on:
      - s3
    links:
      - s3

  pg_wal_perftest:
    build:
      dockerfile: docker/pg_tests/Dockerfile_wal_perftest
      context: .
    image: wal-g/wal_perftest
    container_name: wal-g_pg_wal_perftest
    depends_on:
      - s3
    links:
      - s3

  pg_backup_perftest:
    build:
      dockerfile: docker/pg_tests/Dockerfile_backup_perftest
      context: .
    image: wal-g/backup_perftest
    container_name: wal-g_pg_backup_perftest
    depends_on:
      - s3
    links:
      - s3

  pg_delete_before_name_find_full_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_delete_before_name_find_full_test
      context: .
    image: wal-g/delete_before_name_find_full_test
    container_name: wal-g_pg_delete_before_name_find_full_test
    depends_on:
      - s3
    links:
      - s3

  pg_delete_retain_full_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_delete_retain_full_test
      context: .
    image: wal-g/delete_retain_full_test
    container_name: wal-g_pg_delete_retain_full_test
    depends_on:
      - s3
    links:
      - s3

  pg_full_backup_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_full_backup_test
      context: .
    image: wal-g/full_backup_test
    container_name: wal-g_pg_full_backup_test
    depends_on:
      - s3
    links:
      - s3

  pg_ssh_backup_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_ssh_backup_test
      context: .
    image: wal-g/ssh_backup_test
    container_name: wal-g_pg_ssh_backup_test
    depends_on:
      - ssh
    links:
      - ssh

  pg_receive_wal_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_receive_wal_test
      context: .
    image: wal-g/receive_wal_test
    container_name: wal-g_pg_receive_wal_test
    depends_on:
      - s3
    links:
      - s3

  pg_full_backup_rating_composer_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_full_backup_rating_composer_test
      context: .
    image: wal-g/full_backup_rating_composer_test
    container_name: wal-g_pg_full_backup_rating_composer_test
    depends_on:
      - s3
    links:
      - s3

  pg_delete_before_time_find_full_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_delete_before_time_find_full_test
      context: .
    image: wal-g/delete_before_time_find_full_test
    container_name: wal-g_pg_delete_before_time_find_full_test
    depends_on:
      - s3
    links:
      - s3

  pg_delete_without_confirm_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_delete_without_confirm_test
      context: .
    image: wal-g/delete_without_confirm_test
    container_name: wal-g_pg_delete_without_confirm_test
    depends_on:
      - s3
    links:
      - s3

  pg_ghost_table_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_ghost_table_test
      context: .
    image: wal-g/ghost_table_test
    container_name: wal-g_pg_ghost_table_test
    depends_on:
      - s3
    links:
      - s3

  pg_config_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_config_test
      context: .
    image: wal-g/config_test
    container_name: wal-g_pg_config_test
    depends_on:
      - s3
    links:
      - s3

  pg_delete_end_to_end_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_delete_end_to_end_test
      context: .
    image: wal-g/delete_end_to_end_test
    container_name: wal-g_pg_delete_end_to_end_test
    depends_on:
      - s3
    links:
      - s3

  pg_delta_backup_fullscan_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_delta_backup_fullscan_test
      context: .
    image: wal-g/delta_backup_fullscan_test
    container_name: wal-g_pg_delta_backup_fullscan_test
    depends_on:
      - s3
    links:
      - s3

  pg_several_delta_backups_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_several_delta_backups_test
      context: .
    image: wal-g/several_delta_backups_test
    container_name: wal-g_pg_several_delta_backups_test
    depends_on:
      - s3
    links:
      - s3

  pg_several_delta_backups_reverse_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_several_delta_backups_reverse_test
      context: .
    image: wal-g/several_delta_backups_reverse_test
    container_name: wal-g_pg_several_delta_backups_reverse_test
    depends_on:
      - s3
    links:
      - s3

  pg_crypto_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_crypto_test
      context: .
    image: wal-g/crypto_test
    container_name: wal-g_pg_crypto_test
    depends_on:
      - s3
    links:
      - s3

  pg_delete_retain_find_full_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_delete_retain_find_full_test
      context: .
    image: wal-g/delete_retain_find_full_test
    container_name: wal-g_pg_delete_retain_find_full_test
    depends_on:
      - s3
    links:
      - s3

  pg_delta_backup_wal_delta_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_delta_backup_wal_delta_test
      context: .
    image: wal-g/delta_backup_wal_delta_test
    container_name: wal-g_pg_delta_backup_wal_delta_test
    depends_on:
      - s3
    links:
      - s3

  pg_wale_compatibility_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_wale_compatibility_test
      context: .
    image: wal-g/wale_compatibility_test
    container_name: wal-g_pg_wale_compatibility_test
    depends_on:
      - s3
    links:
      - s3

  pg_wale_tablespace_compatibility_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_wale_tablespace_compatibility_test
      context: .
    image: wal-g/wale_tablespace_compatibility_test
    container_name: wal-g_pg_wale_tablespace_compatibility_test
    env_file:
      - docker/common/common_walg.env
      - docker/pg_tests/walg.env
    depends_on:
      - s3
    links:
      - s3

  pg_tablespace_support_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_tablespace_support_test
      context: .
    image: wal-g/tablespace_support_test
    container_name: wal-g_pg_tablespace_support_test
    env_file:
      - docker/common/common_walg.env
      - docker/pg_tests/walg.env
    depends_on:
      - s3
    links:
      - s3

  pg_catchup_test:
    build:
      dockerfile: docker/pg_tests/Dockerfile_catchup_test
      context: .
    image: wal-g/catchup_test
    container_name: wal-g_pg_catchup_test
    depends_on:
      - s3
    links:
      - s3

  mysql:
    build:
      dockerfile: docker/mysql/Dockerfile
      context: .
    image: wal-g/mysql
    container_name: wal-g_mysql

  mysql_tests:
    build:
      dockerfile: docker/mysql_tests/Dockerfile
      context: .
    security_opt:
      - seccomp:unconfined
    image: wal-g/mysql_tests
    container_name: wal-g_mysql_tests
    env_file:
      - docker/common/common_walg.env
    depends_on:
      - s3
      - s3-another
    links:
      - s3
      - s3-another

  mariadb:
    build:
      dockerfile: docker/mariadb/Dockerfile
      context: .
    image: wal-g/mariadb
    container_name: wal-g_mariadb

  mariadb_tests:
    build:
      dockerfile: docker/mariadb_tests/Dockerfile
      context: .
    security_opt:
      - seccomp:unconfined
    image: wal-g/mariadb_tests
    container_name: wal-g_mariadb_tests
    env_file:
      - docker/common/common_walg.env
    depends_on:
      - s3
    links:
      - s3

  fdb:
    image: foundationdb/foundationdb
    container_name: wal-g_fdb
    volumes:
      - fdb_volume:/var/fdb

  fdb_tests:
    build:
      dockerfile: docker/fdb_tests/Dockerfile
      context: .
    image: wal-g/fdb_tests
    container_name: wal-g_fdb_tests
    volumes:
      - fdb_volume:/var/fdb
    depends_on:
      - fdb

  redis:
    build:
      dockerfile: docker/redis/Dockerfile
      context: .
    image: wal-g/redis
    container_name: wal-g_redis

  redis_tests:
    build:
      dockerfile: docker/redis_tests/Dockerfile
      context: .
    image: wal-g/redis_tests
    container_name: wal-g_redis_tests
    env_file:
      - docker/common/common_walg.env
    depends_on:
      - s3
    links:
      - s3
