version: '3'

services:
  golang:
    build:
      dockerfile: ./docker/golang/Dockerfile
      context: .
    image: wal-g/golang
    container_name: wal-g_golang

  ubuntu:
    build:
      dockerfile: ./docker/ubuntu/Dockerfile
      context: .
    image: wal-g/ubuntu
    container_name: wal-g_ubuntu

  s3:
    image: minio/minio
    container_name: wal-g_s3
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    entrypoint: sh
    command: >
      -c 'mkdir -p /export/fullbucket
      &&  mkdir -p /export/fullscandeltabucket
      &&  mkdir -p /export/waldeltabucket
      &&  mkdir -p /export/deleteretainfullbucket
      &&  mkdir -p /export/deleteretainfindfullbucket
      &&  mkdir -p /export/deletebeforenamefindfullbucket
      &&  mkdir -p /export/deletebeforetimefindfullbucket
      &&  mkdir -p /export/deletewithoutconfirm
      &&  mkdir -p /export/deleteendtoendbucket
      &&  /usr/bin/minio server /export'

  pg:
    build:
      dockerfile: ./docker/pg/Dockerfile
      context: .
    image: wal-g/pg
    container_name: wal-g_pg
    env_file:
      - docker/pg/walg.env
    depends_on:
      - s3
    links:
      - s3
