name: Cross build

on: [ push, pull_request, workflow_dispatch]

env:
  GO_VERSION: "1.25"
  GOEXPERIMENT: jsonv2
  GOOS: windows
  LIBSODIUM_VERSION: "1.0.20"

jobs:
  build:
    name: cross build smoke test
    runs-on: windows-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v5

      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Build dependencies
        run: |
          go get -v -t ./...
          make deps
          curl "https://github.com/jedisct1/libsodium/releases/download/${{ env.LIBSODIUM_VERSION }}-RELEASE/libsodium-${{ env.LIBSODIUM_VERSION }}-mingw.tar.gz" -o "libsodium-${{ env.LIBSODIUM_VERSION }}-mingw.tar.gz"
          tar xfz libsodium-${{ env.LIBSODIUM_VERSION }}-mingw.tar.gz
          mv libsodium-win64/include ./
          mv libsodium-win64/lib ./
          rm -r .\libsodium-*

      - name: Run unittests
        run: |
          make unittest

      - name: Build wal-g for SQL Server and PostgreSQL
        run: |
          make sqlserver_build pg_build