name: Cross build

on: [ push, pull_request, workflow_dispatch]

env:
  GO_VERSION: "1.25"
  GOEXPERIMENT: jsonv2
  GOOS: windows

jobs:
  build:
    name: cross build smoke test
    runs-on: windows-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v5

      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Build dependencies
        shell: bash
        run: |
          go get -v -t ./...
          make deps
          ./link_libsodium.sh

      - name: Run unittests
        run: |
          make unittest

      - name: Build wal-g for SQL Server and PostgreSQL
        run: |
          make sqlserver_build pg_build