name: Docker tests

on: [ push, pull_request, workflow_dispatch ]

jobs:
  parallel:
    uses: ./.github/workflows/dockertests.yml
    with:
      command-json-array: >
        [
        "make TEST=\"pg_ready_rename_test\" pg_integration_test",
        "make TEST=\"pg_backup_mark_impermanent_test\" pg_integration_test",
        "make TEST=\"pg_backup_mark_permanent_test\" pg_integration_test",
        "make TEST=\"pg_config_test\" pg_integration_test",
        "make TEST=\"pg_crypto_test\" pg_integration_test",
        "make TEST=\"pg_copy_all_test\" pg_integration_test",
        "make TEST=\"pg_copy_backup_test\" pg_integration_test",
        "make TEST=\"pg_delta_backup_wal_delta_test\" pg_integration_test",
        "make TEST=\"pg_full_backup_test\" pg_integration_test",
        "make TEST=\"pg_full_backup_streamed_test\" pg_integration_test",
        "make TEST=\"pg_partial_restore_test\" pg_integration_test",
        "make TEST=\"pg_remote_backup_test\" pg_integration_test",
        "make TEST=\"pg_remote_backup_without_files_metadata_test\" pg_integration_test",
        "make TEST=\"pg_ssh_backup_test\" pg_integration_test",
        "make TEST=\"pg_transfer_backup_test\" pg_integration_test",
        "make TEST=\"pg_receive_wal_test\" pg_integration_test",
        "make TEST=\"pg_full_backup_copy_composer_test\" pg_integration_test",
        "make TEST=\"pg_full_backup_rating_composer_test\" pg_integration_test",
        "make TEST=\"pg_full_backup_database_composer_test\" pg_integration_test",
        "make TEST=\"pg_full_backup_failover_storage_test\" pg_integration_test",
        "make TEST=\"pg_delete_before_name_find_full_test\" pg_integration_test",
        "make TEST=\"pg_delete_before_permanent_delta_multist_test\" pg_integration_test",
        "make TEST=\"pg_delete_before_permanent_delta_test\" pg_integration_test",
        "make TEST=\"pg_delete_before_permanent_full_test\" pg_integration_test",
        "make TEST=\"pg_delete_before_time_find_full_test\" pg_integration_test",
        "make TEST=\"pg_delete_end_to_end_test\" pg_integration_test",
        "make TEST=\"pg_delete_garbage_multist_test\" pg_integration_test",
        "make TEST=\"pg_delete_garbage_test\" pg_integration_test",
        "make TEST=\"pg_delete_retain_find_full_test\" pg_integration_test",
        "make TEST=\"pg_delete_retain_full_multist_test\" pg_integration_test",
        "make TEST=\"pg_delete_retain_full_test\" pg_integration_test",
        "make TEST=\"pg_delete_retain_after_test\" pg_integration_test",
        "make TEST=\"pg_delete_target_delta_find_full_test\" pg_integration_test",
        "make TEST=\"pg_delete_target_delta_multist_test\" pg_integration_test",
        "make TEST=\"pg_delete_target_delta_test\" pg_integration_test",
        "make TEST=\"pg_delete_target_test\" pg_integration_test",
        "make TEST=\"pg_delete_without_confirm_test\" pg_integration_test",
        "make TEST=\"pg_delta_backup_fullscan_test\" pg_integration_test",
        "make TEST=\"pg_ghost_table_test\" pg_integration_test",
        "make TEST=\"pg_several_delta_backups_test\" pg_integration_test",
        "make TEST=\"pg_several_delta_backups_reverse_test\" pg_integration_test",
        "make TEST=\"pg_storage_swift_test\" pg_integration_test",
        "make TEST=\"pg_storage_ssh_test\" pg_integration_test",
        "make TEST=\"pg_wale_compatibility_test\" pg_integration_test",
        "make TEST=\"pg_backup_mark_permanent_no_error_test\" pg_integration_test",
        "make TEST=\"pg_daemon_test\" pg_integration_test",
        "make TEST=\"pg_daemon_backup_and_restore_test\" pg_integration_test",
        "make TEST=\"pg_daemon_client_test\" pg_integration_test",
        "make TEST=\"prefetch_test\" pg_integration_test",
        "make mongo_test",
        "make MONGO_VERSION=\"8.0.3\" MONGO_REPO=\"repo.mongodb.org\" MONGO_PACKAGE=\"mongodb-org\" mongo_catch_up_features",
        "make MONGO_VERSION=\"8.0.3\" MONGO_REPO=\"repo.mongodb.com\" MONGO_PACKAGE=\"mongodb-enterprise\" mongo_catch_up_features",
        "make MONGO_VERSION=\"8.0.3\" MONGO_REPO=\"repo.mongodb.com\" MONGO_PACKAGE=\"mongodb-enterprise\" mongo_binary_features",
        "make MONGO_VERSION=\"8.0.3\" MONGO_REPO=\"repo.mongodb.org\" MONGO_PACKAGE=\"mongodb-org\" mongo_logical_features",
        "make MONGO_VERSION=\"8.0.3\" MONGO_REPO=\"repo.mongodb.com\" MONGO_PACKAGE=\"mongodb-enterprise\" mongo_partial_features",
        "make MONGO_VERSION=\"7.0.15\" MONGO_REPO=\"repo.mongodb.org\" MONGO_PACKAGE=\"mongodb-org\" mongo_catch_up_features",
        "make MONGO_VERSION=\"7.0.15\" MONGO_REPO=\"repo.mongodb.com\" MONGO_PACKAGE=\"mongodb-enterprise\" mongo_catch_up_features",
        "make MONGO_VERSION=\"7.0.15\" MONGO_REPO=\"repo.mongodb.com\" MONGO_PACKAGE=\"mongodb-enterprise\" mongo_binary_features",
        "make MONGO_VERSION=\"7.0.15\" MONGO_REPO=\"repo.mongodb.org\" MONGO_PACKAGE=\"mongodb-org\" mongo_logical_features",
        "make MONGO_VERSION=\"7.0.15\" MONGO_REPO=\"repo.mongodb.com\" MONGO_PACKAGE=\"mongodb-enterprise\" mongo_partial_features",
        "make redis_test",
        "make FEATURE=\"aof_backup\" IMAGE_TYPE=\"aof\" REDIS_VERSION=\"7.0.15\" redis_features",
        "make FEATURE=\"aof_backup\" IMAGE_TYPE=\"aof\" REDIS_VERSION=\"7.2.4\" redis_features",
        "make FEATURE=\"rdb_backup\" IMAGE_TYPE=\"rdb\" REDIS_VERSION=\"6.2.4\" redis_features",
        "make FEATURE=\"rdb_backup\" IMAGE_TYPE=\"rdb\" REDIS_VERSION=\"7.0.15\" redis_features",
        "make FEATURE=\"rdb_backup\" IMAGE_TYPE=\"rdb\" REDIS_VERSION=\"7.2.4\" redis_features",
        "make TEST=\"pg_wale_tablespace_compatibility_test\" pg_integration_test",
        "make TEST=\"pg_tablespace_support_test\" pg_integration_test",
        "make TEST=\"pg_walg_tablespace_restore_spec_test\" pg_integration_test",
        "make TEST=\"pg_wal_perftest\" pg_integration_test",
        "make TEST=\"pg_wal_perftest_with_throttling\" pg_integration_test",
        "make TEST=\"pg_backup_perftest\" pg_integration_test",
        "make TEST=\"pg_catchup_test\" pg_integration_test",
        "make TEST=\"pg_wal_restore_test\" pg_integration_test",
        "make MYSQL_TEST=mysql_base_tests mysql_integration_test",
        "make MYSQL_TEST=mysql_delete_tests mysql_integration_test",
        "make MYSQL_TEST=mysql_copy_tests mysql_integration_test",
        "make USE_BROTLI= USE_LZO= USE_LIBSODIUM= MYSQL_TEST=mysql8_tests mysql8_integration_test",
        "make mariadb_test",
        "make gp_test",
        "make cloudberry_test",
        "make st_test",
        "make TEST=\"pg_pgbackrest_backup_fetch_test\" pg_integration_test",
        "make etcd_test",
        "make orioledb_integration_test",
        ]
