name: Docker tests

on:
  workflow_call:
    inputs:
      command-json-array:
        required: true
        type: string

env:
  CACHE_FOLDER: ~/docker-images-${{ github.sha }}
  CACHE_FILE_UBUNTU_18_04: ~/docker-images-${{ github.sha }}/wal-g_ubuntu-18.04.tgz
  CACHE_FILE_UBUNTU_20_04: ~/docker-images-${{ github.sha }}/wal-g_ubuntu-20.04.tgz
  CACHE_FILE_GOLANG: ~/docker-images-${{ github.sha }}/wal-g_golang.tgz
  CACHE_FILE_DOCKER_PREFIX: ~/docker-images-${{ github.sha }}/docker_prefix.tgz
  IMAGE: wal-g/docker_prefix
  IMAGE_GOLANG: wal-g/golang
  IMAGES_CACHE_KEY: docker-images-${{ github.sha }}
  GO_VERSION: "1.25"
  LIBSODIUM_VERSION: "1.0.20"

jobs:
  buildimages:
    name: Build images
    runs-on: ubuntu-latest
    steps:
      #  use cache to pass docker images to the test jobs
      - name: Docker images caching
        id: cache-images
        uses: actions/cache@v5
        with:
          path: |
            ${{ env.CACHE_FILE_DOCKER_PREFIX }}
            ${{ env.CACHE_FILE_UBUNTU_18_04 }}
            ${{ env.CACHE_FILE_UBUNTU_20_04 }}
            ${{ env.CACHE_FILE_GOLANG }}
          key: ${{ env.IMAGES_CACHE_KEY }}

      - name: Install deps
        if: steps.cache-images.outputs.cache-hit != 'true'
        run: sudo apt clean && sudo apt-get install liblzo2-dev

      - name: Check out code into the Go module directory
        if: steps.cache-images.outputs.cache-hit != 'true'
        uses: actions/checkout@v6

      - name: Set up Go 1.x
        if: steps.cache-images.outputs.cache-hit != 'true'
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Get dependencies
        if: steps.cache-images.outputs.cache-hit != 'true'
        run: |
          go get -v -t ./...

      # build images
      - name: Build images
        if: steps.cache-images.outputs.cache-hit != 'true'
        run: make pg_save_image
    env:
      USE_BROTLI: 1
      USE_LZO: 1

  test:
    name: test
    runs-on: ubuntu-latest
    needs: [ buildimages ]
    strategy:
      matrix:
        # GH Actions lack of complex types support for inputs.
        # Workaround https://github.com/orgs/community/discussions/11692#discussioncomment-3187271
        command: ${{ fromJSON(inputs.command-json-array) }}
      # do not cancel all tests if one failed
      fail-fast: false
    steps:
      - name: Install deps
        run: sudo apt-get install liblzo2-dev

      - name: Check out code into the Go module directory
        uses: actions/checkout@v6

      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      # load docker images
      - name: Load docker images
        id: cache-images
        uses: actions/cache@v5
        with:
          path: |
            ${{ env.CACHE_FILE_DOCKER_PREFIX }}
            ${{ env.CACHE_FILE_UBUNTU_18_04 }}
            ${{ env.CACHE_FILE_UBUNTU_20_04 }}
            ${{ env.CACHE_FILE_GOLANG }}
          key: ${{ env.IMAGES_CACHE_KEY }}

      - name: Fail if no cached images
        if: steps.cache-images.outputs.cache-hit != 'true'
        run: |
          echo "Failed to fetch cached docker images. Will now exit..."
          exit 1

      - name: Run test
        run: ${{ matrix.command }}
    env:
      USE_BROTLI: 1
      USE_LIBSODIUM: 1
      USE_LZO: 1
