name: Build MySQL Exporter

on: [push, pull_request]

env:
  GO_VERSION: "1.25"

jobs:
  build-exporter:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cmd/mysql/exporter
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: cmd/mysql/exporter/go.sum

      - name: Build
        run: go build -v ./...

      - name: Vet
        run: go vet ./...
