name: Unit tests

on: [ push, pull_request, workflow_dispatch ]

env:
  GO_VERSION: "1.25"
  USE_BROTLI: 1

jobs:
  unittest:
    name: all_unittests
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y liblzo2-dev

      - name: Check out code into the Go module directory
        uses: actions/checkout@v6

      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go

      - name: Get dependencies
        run: |
          go get -v -t ./...

      - name: Test
        run: make all_unittests
        env:
          USE_BROTLI: 1
          USE_LIBSODIUM: 1
          USE_LZO: 1
          TEST_MODIFIER: -race

